@startuml

abstract class BusDevice{
. . . 
}


class ConfigFileReader extends BusDevice{
	-configFile: File
	-set(ID: String, :Value) boolean
	-get(ID: String): value
} 

class SignalCollector extends BusDevice{
	-signalsList: List
}


@enduml
