@startuml
actor User

activate User
User ->> Terminal: Open webpage of software
activate Terminal

Terminal ->> Webserver: request webpage with all documents
activate Webserver

Terminal <<-- Webserver: send page (html, JS) back
Webserver -> Terminal: request VINJAB-Cookie
Terminal --> Webserver: return cookie or null
alt signature not found
	Webserver -> Webserver: createRandomSignature()
	activate Webserver
		Webserver -> Webserver: Signature
	deactivate Webserver
	Webserver -> Terminal: send signature
	Terminal -> Terminal: create cookie with signature
end

create ":Proxy"
Webserver -> ":Proxy": <<creates>>
deactivate Webserver

activate ":Proxy"
	":Proxy" -> ":Proxy": createMessage(request, signature)
	activate ":Proxy"
		":Proxy" --> ":Proxy": message
	deactivate ":Proxy"
	":Proxy" -> Bus: subscribe(database)
	activate Bus
    	Bus -> ":Proxy"
    deactivate Bus
	":Proxy" ->> Bus: publish(message)
deactivate ":Proxy"

activate Bus
	Bus ->> Database: handleMessage(message)
deactivate Bus

activate Database
	Database -> Database: searchSignature(signature)
	activate Database
		Database --> Database: Config
	deactivate Database

	alt signature equals null
		Database -> Database: createConfig(signature, defaultConfig)
		activate Database
			Database -> Database
		deactivate Database
		
	end
	Database -> Database: createMessage(answer, config)
	activate Database
		Database -> Database: message
	deactivate Database
	Database ->> Bus: publish(message)
deactivate Database	

activate Bus
	Bus ->> ":Proxy": handleMessage(message)
deactivate Bus

activate ":Proxy"
	":Proxy" ->> ":Proxy": changeSubscriptions(signature)
	activate ":Proxy"
		":Proxy" -->> ":Proxy"
	deactivate ":Proxy"
	Terminal <<- ":Proxy": initiate WebRTC connection
	Terminal <<- ":Proxy": send config

	loop
		Terminal <-- ":Proxy": send live data
		Terminal --> User: Show dashes with config	

		alt config changed
			Terminal ->> ":Proxy": send new config
			":Proxy" -> ":Proxy": createMessage(newConfig, config)
			activate ":Proxy"
				":Proxy" --> ":Proxy": Message
			deactivate ":Proxy"
			":Proxy" -> ":Proxy": changeSubscribtions(config)
			activate ":Proxy"
				":Proxy" --> ":Proxy"
			deactivate ":Proxy"
			":Proxy" ->> Bus: publish(message)
			activate Bus
				Bus ->> Database: handleMessage(message)
			deactivate Bus
			
			activate Database
				Database -> Database: adjustConfig(config)
				activate Database
					Database->Database
				deactivate Database
			deactivate Database
		end
	end
deactivate ":Proxy"

deactivate User
deactivate Terminal
deactivate Database
@enduml
