@startuml
actor User

activate User
User --> Terminal: Open webpage of software
activate Terminal

Terminal --> Webserver: request webpage with all documents
activate Webserver

Terminal <-- Webserver: send page (html, JS) back
Webserver --> Terminal: request VINJAB-Cookie
Terminal --> Webserver: return cookie or null
alt signature not found
	Webserver -> Webserver: create random signature for new device
	Webserver --> Terminal: send signature
	Terminal -> Terminal: create cookie with signature
end

create ":Proxy"
Webserver --> ":Proxy": <<creates>>
activate ":Proxy"
deactivate Webserver

":Proxy" -> Bus: Request config of signature
deactivate ":Proxy"
activate Bus
Bus -> Database: Push request
deactivate Bus
Database -> Database: Search for signature

alt signature found
	Bus <- Database: Push config	
	activate Bus
else signature not found
	deactivate Bus
	Database -> Database: create default config
	Database -> Bus: Push config
	activate Bus
end

Bus -> ":Proxy": Push config
deactivate Bus
activate ":Proxy"

":Proxy" --> ":Proxy": Set subscriptions after the config
Terminal <-- ":Proxy": initiate WebRTC connection
Terminal <-- ":Proxy": send config

loop
	Terminal <-- ":Proxy": send live data
	Terminal --> User: Show dashes with config	

	alt config changed
		Terminal --> ":Proxy": send new config
		":Proxy" --> Bus: push new config
		activate Bus
		":Proxy" --> ":Proxy": adjust subscriptions after config
		Bus --> Database: push new config
		deactivate Bus
		activate Database
		Database --> Database: adjust config of signature
		deactivate Database
	end
end

deactivate User
deactivate Terminal
deactivate ":Proxy"
@enduml