@startuml


class Statistics {
	-topic: Topic
	-values: Map<Date, Value>
	+Statistics(map: Map<Date, Value>)
	+data(): Map<Date, Value>
	+getTimestamps(): Array of Date
	+getValues(): Array of Value
}

abstract class BusAccess

class TerminalProxy {

}

class Value {
	-value: double
	-String: unit
	+getValue(): double
	+getUnit(): String
}

class DatabaseConnection {
	-levelDB: LevelDB
	+DatabaseConnection(pdbs: LevelDB) <<constructor>>
	-getAllData(topic: Topic): Message
	-getAverage(topic: Topic): Message
	-getData(tid: TopicID, startTime: Date, endTime: Date): StatisticMessage

}

BusAccess <|-- DatabaseConnection
BusAccess <|-- TerminalProxy

@enduml