@startuml


Grid "1"*--"*" Widget

abstract class BusAccess

abstract class Widget extends BusAccess{
    -name: String
    +_create()
    +_destroy()
    +{abstract} update(value)
}

abstract class NumberDash extends Widget{
    +{abstract} update(value: int)
}

abstract class BooleanDash extends Widget{
    +{abstract} update(value: bool)
}

class LinearGauge extends NumberDash{
}

class RadialGauge extends NumberDash{
}

class WarningSign extends BooleanDash{
}

class Grid << (S,#FF7700) Singleton,Serializable >> {
    +add_widget(:Widget, :Options)
    +remove_widget(:Widget, callback: Function)
	-gridster: Gridster
}

'-------------------------------------'

Settings *-- Table
Settings --> Grid

class Settings <<Singleton>> extends BusAccess{
	-availableSignals: List
	-config: Config
	-changeConfig()
}

abstract class Table {
    -objects[]: Array of Objects
    +addObject(:Object)
    +removeObject(:Object)
}


'-------------------------------------'



@enduml
