@startuml




GridView "1"*--"*" Widget

abstract class BusDevice

abstract class Widget extends BusDevice{
    -name: String
    +{abstract}_create()
    +{abstract}_destroy()
}

abstract class NumberDash extends Widget{
}

abstract class BooleanDash extends Widget{
}

class GridView <<  Singleton,Serializable >> extends ViewFrame{
    +add_widget(:Widget, :Options)
    +remove_widget(:Widget, callback: Function)
	-gridster: Gridster
}

'-------------------------------------'

SettingsView "1"*--"1..*" Table
SettingsView o--"1" GridView

class SettingsView <<Singleton>> extends BusDevice, ViewFrame{
	-availableSignals: List
	-config: Config
	-changeConfig()
}

abstract class Table {
    -objects[]: Array of Objects
    +addObject(:Object)
    +removeObject(:Object)
}



@enduml
