Component diagram 2

@startuml

interface BusAcces{
	...
}

abstract class VirtualSensor {
	+activ(pActive: Boolean) : Boolean
	-initialize()
	-provideValuesFromBus(): double[]
	-computeValue(values: double[]) : double
	-pushOnBus(message: Message);
}

class AverageComputation {
	type: TopicID
	+setType(pType: TopicID)
}

class TripMileage {
	counter: double
}


VirtualSensor <|-- FuelConsumption
VirtualSensor <|-- TripMileage


BusAcces <|.. VirtualSensor

@enduml

