Component diagram 2

@startuml

abstract class BusDevice {
	...
}

abstract class VirtualSensor {
	-topic: Topic
	-initialize()
	-computeValue(values: Value[]): Value
}

class TripMileage {
	-counter: Value
}

class AverageComputation {
	-avgTopic: Topic
	-updateValue(values: Value);
	-buildDBRequest(): DBRequestMessage
}

class RemainingMiles {
	-buildDBRequest(): DBRequestMessage
}

class Statistics {
	-topic: Topic
	-values: Map<Date, Value>
	+Statistics(pTopic: Topic, pValues: Map<Date, Value>)
	+data(): Map<Date, Value>
	+getTimestamps(): Array of Date
	+getValues(): Array of Value
}

VirtualSensor <|-- TopicOverTime
VirtualSensor <|-- FuelConsumption
VirtualSensor <|-- TripMileage
VirtualSensor <|-- AverageComputation
VirtualSensor <|-- RemainingMiles

BusDevice <|-- VirtualSensor

@enduml

