@startuml

class Website <<(W,#FF7700)HTML>>{
}

class StatusBarFrame {
	-elements: List of elements
	+addElement(e: Element, pos: Position): boolean
	+removeElement(e: Element) boolean
}

abstract class ViewFrame {
	-elements: List of elements
	+{abstract} resize(x: integer, y: integer)
}

class MapView extends ViewFrame{
. . .
}

class ParkingView extends ViewFrame{
. . .
}

class GridView extends ViewFrame{
. . .
}

class SettingsView extends ViewFrame{
. . .
}

Website "1"*--"1" StatusBarFrame
Website "1"*--"1" ViewFrame

@enduml
